### ISSUE TITLE
Illegal division by zero at ocr_compare.pl line 372, <$in2> line 20.

### ISSUE THREAD

**Issue by Shreeshrii** [wollmers/ocr-measures#3]
~/tesseract-ocr/ocr-measures$ perl ocr_compare.pl images/hin001.txt images/hin001.tif.txt

ocr_compare.pl Version 0.02

Compare OCR text output against ground truth (GRT):
File 1 (OCR): images/hin001.txt
File 2 (GRT): images/hin001.tif.txt

Illegal division by zero at ocr_compare.pl line 372, <$in2> line 20.

---

~/tesseract-ocr/ocr-measures$  perl ocr_compare.pl images/hin001.tif.txt images/hin001.txt
ocr_compare.pl Version 0.02

Compare OCR text output against ground truth (GRT):
File 1 (OCR): images/hin001.tif.txt
File 2 (GRT): images/hin001.txt

Illegal division by zero at ocr_compare.pl line 372, <$in2> line 15.

---

![hin001](https://cloud.githubusercontent.com/assets/5095331/13809447/f3c786f0-eb90-11e5-910d-342a398395a0.png)

[hin001.tif.txt](https://github.com/wollmers/ocr-measures/files/175729/hin001.tif.txt)
[hin001.txt](https://github.com/wollmers/ocr-measures/files/175730/hin001.txt)

**Comment by wollmers** [comment]
Thanks for reporting.

Works now with your files and patch https://github.com/wollmers/ocr-measures/commit/2e41e2225ff7da6d47e81120d7c1e0e365faaca3
